name: Test

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        runner:
          - windows-latest
        deno-version:
          - "1.42.x"
          - "1.x"
    runs-on: ${{ matrix.runner }}
    steps:

      - name: Setup environment
        if: runner.os == 'Windows'
        run: |
          git config --global core.autocrlf false
          echo "DENO_DIR=$env:LOCALAPPDATA\deno" >> "$env:GITHUB_ENV"

      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.deno-version }}"

      - uses: actions/cache@v4
        with:
          key: deno-${{ runner.os }}-${{ matrix.deno-version }}-${{ hashFiles('test.lock', '.github/workflows/**') }}
          restore-keys: deno-${{ runner.os }}-${{ matrix.deno-version }}-
          path: |
            ${{ env.DENO_DIR }}

      - name: Check
        run: deno task check

      - name: Check slow types
        run: deno task check:publish

      - name: Test
        run: deno task test:coverage

      - name: Coverage
        run: deno task coverage --lcov --output=./lcov

      - uses: codecov/codecov-action@v4
        with:
          files: ./lcov
          token: ${{ secrets.CODECOV_TOKEN }}
