name: Test

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        runner:
          - windows-latest
        deno:
          - version: "1.x"
            unsupported_lockfile: true
          - version: "canary"
    runs-on: ${{ matrix.runner }}
    steps:

      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.deno.version }}"

      - name: Remove lock file
        if: matrix.deno.unsupported_lockfile
        run: rm deno.lock

      - name: Check
        run: deno task check

      - name: Check slow types
        run: deno task check:publish --allow-dirty

  test:
    needs: check
    strategy:
      matrix:
        runner:
          - windows-latest
        deno:
          - version: "1.42.x"
            unsupported_lockfile: true
          - version: "1.x"
            unsupported_lockfile: true
          - version: "canary"
    runs-on: ${{ matrix.runner }}
    steps:

      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.deno.version }}"

      - name: Remove lock file
        if: matrix.deno.unsupported_lockfile
        run: rm deno.lock

      - name: Test
        run: deno task test:coverage

      - name: Coverage
        run: deno task coverage --lcov --output=./lcov

      - uses: codecov/codecov-action@v4
        with:
          files: ./lcov
          token: ${{ secrets.CODECOV_TOKEN }}
