name: Test

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        runner:
          - windows-latest
        deno-version:
          - "1.42.x"
          - "1.x"
    runs-on: ${{ matrix.runner }}
    steps:

      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.deno-version }}"

      - name: Check
        run: deno task check

      - name: Check slow types
        run: deno task check:publish

      - name: Test
        run: deno task test:coverage

      - name: Coverage
        run: deno task coverage --lcov --output=./lcov

      - uses: codecov/codecov-action@v4
        with:
          files: ./lcov
          token: ${{ secrets.CODECOV_TOKEN }}
